AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - bin/*
    - 'vendor/**/*'
    - 'log/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false