default: &default
  adapter: postgresql
  encoding: unicode
  host: postgresql-db
  port: 5432
  username: postgres
  password: mysecretpassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_service_development

test:
  <<: *default
  database: blog_service_test